require 'simplest_photo/model/has_attachment'
require 'simplest_photo/model/attachment'
require 'simplest_photo/model/validations'
require 'simplest_photo/model/photo'
require 'simplest_photo/model/photo_attachment'
require 'simplest_photo/model/photo_cropping'
require 'simplest_photo/has_photo'
require 'simplest_photo/url_helper'
